# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: ""
title: GLOSE
email: glose@inria.fr
author: Safran, Inria & CNRS
description: TODO
copyright: 'Copyright &copy; 2018-2021 Safran / Inria  / CNRS. All Rights Reserved.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: email
    url: mailto:glose@inria.fr

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
