# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: ""
title: GLOSE
email: glose@inria.fr
author: Safran, Inria & CNRS
description: TODO
copyright: 'Copyright &copy; 2018-2021 Safran / Inria  / CNRS. All Rights Reserved.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: comment
    url: mailto:glose@inria.fr
  - title: twitter
    url: https://twitter.com/gemocinitiative
  - title: github
    url: https://github.com/gemoc

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

# ------------------------------- #
#   technical meeting Settings    #
# ------------------------------- #
  defaults:
  - scope:
      path: "_tm"
