# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: ""
title: GLOSE
email: glose@inria.fr
author: Safran, Inria & CNRS
description: TODO
copyright: 'Copyright &copy; 2017-2020 Safran / Inria  / CNRS. All Rights Reserved.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/gemocinitiative
  - title: github
    url: https://github.com/gemoc

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
